#!/bin/sh

. git-simple-common.sh

if [ X"$1" = X"-h" ]; then
	echo "Usage: git publish [branch] [remote]"
	echo "  Publishes a branch to the remote. If no remote is supplied, assumes origin."
	exit 0
fi

BRANCH=$1
REMOTE=$2
[ -z ${BRANCH} ] && die "No branch was specified."
[ -z ${REMOTE} ] && REMOTE="origin"

FOUND_REMOTE_BRANCH=0
for br in `remote_branch_names | grep $REMOTE`; do
    branch=`echo $br | sed -e s,.*/,,g`
    [ X"$branch" = X"$BRANCH" ] && FOUND_REMOTE_BRANCH=1
done

[ ${FOUND_REMOTE_BRANCH} -eq 1 ] && die "Branch '$BRANCH' is already published."

# TODO: Support multiple remotes
git push $REMOTE $BRANCH
